---
- hosts: vagrant
  gather_facts: false
  become: true

  tasks:
    - name: ensure beginning placeholder
      lineinfile:
        path: /etc/hosts
        line: '### host automation update placeholder - start'
        insertafter: EOF

    - name: ensure end placeholder
      lineinfile:
        path: /etc/hosts
        line: '### host automation update placeholder - end'
        insertafter: '### host automation update placeholder - start'

    - name: ensure each vm from vagrant is present in all vms hosts file
      lineinfile:
        path: /tmp/hosts
        regexp: '^{{item}}(.*){{hostvars[item]["ht_name"]}}.abhinav.local(.*){{hostvars[item]["ht_name"]}}(.*)'
        line: '{{item}} {{hostvars[item]["ht_name"]}}.abhinav.local {{hostvars[item]["ht_name"]}}'
        insertbefore: '### host automation update placeholder - end'
      when: item != inventory_hostname or hostvars[item]['ht_name'] != item
      loop: "{{groups['vagrant']}}"
